### ISSUE TITLE
Crash on configure

### ISSUE THREAD

**Issue by Aztorius** [tranquilit/tis-sysvolsync#2]
On CentOS 7 with prebuilt package and on CentOS 8 with built package there is a crash when doing : 
`/opt/tis-sysvolsync/sysvolsync.py configure`

The error is reproduced below : 
`2020-10-21 12:07:59,536 CRITICAL Error in data : CSRF Error
 for path system/status
Traceback (most recent call last):
  File "/opt/tis-sysvolsync/sysvolsync.py", line 409, in <module>
    main()
  File "/opt/tis-sysvolsync/sysvolsync.py", line 348, in main
    syncthing = SyncThing()
  File "/opt/tis-sysvolsync/sysvolsync.py", line 87, in __init__
    self.id = self.get_syncthing_id()
  File "/opt/tis-sysvolsync/sysvolsync.py", line 158, in get_syncthing_id
    return self.syncthing_rest_get('system/status')['myID']
  File "/opt/tis-sysvolsync/sysvolsync.py", line 131, in syncthing_rest_get
    return json.loads(data.content or '{}')
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

Thanks

**Comment by maxxer** [comment]
For the record, this happened to me today with Ubuntu 20. Restarting both services solved

```
systemctl restart tis-sysvolsync
systemctl restart tis-sysvolacl
```
