### ISSUE TITLE
sysvolsync.py configure fails on Debian 11

### ISSUE THREAD

**Issue by Silejonu** [tranquilit/tis-sysvolsync#4]
I followed the guide at https://samba.tranquil.it/doc/fr/samba_advanced_methods/samba_tis_sysvolsync.html to get `tis-sysvolsync` working on Debian 11.

More specifically, I ran:

```bash
sudo apt-get install git python3-requests python3-lxml python3-ldap procps ldb-tools # I obviously had to install the Python 3 packages
git clone https://github.com/tranquilit/tis-sysvolsync
cd tis-sysvolsync/deb
sh createdeb.sh
sudo dpkg -i tis-sysvolsync-1.20.4.deb
sudo systemctl restart tis-sysvolsync.service
sudo systemctl restart tis-sysvolacl.service
sudo /opt/tis-sysvolsync/sysvolsync.py configure
```

When running the last command, I get the following errors:
```bash
2023-03-08 20:59:22,130 INFO ID : SAF4TGP-RAASEMZ-JCYHRWR-ER4G2V4-2WGVTGN-XOVSZ4T-SARXPBP-RLGWCQK
2023-03-08 20:59:22,130 INFO api port : 8385
2023-03-08 20:59:22,130 INFO api key : uq6PEGvoBLjFQgSUhGkCJdq9RJrjOLwN3/V6XXkY9T
2023-03-08 20:59:22,130 INFO data port : 22001
{'Forest': 'mondomaine.lan', 'Domain': 'mondomaine.lan', 'Netbios domain': 'MONDOMAINE', 'DC name': 'debian-dc1.mondomaine.lan', 'DC netbios name': 'DEBIAN-DC1', 'Server site': 'Default-First-Site-Name', 'Client site': 'Default-First-Site-Name'}
Get DRS connections informations from local LDB AD database...
Configuring sync from DEBIAN-DC2 to DEBIAN-DC1
Remote host infos : {'Forest': 'mondomaine.lan', 'Domain': 'mondomaine.lan', 'Netbios domain': 'MONDOMAINE', 'DC name': 'debian-dc2.mondomaine.lan', 'DC netbios name': 'DEBIAN-DC2', 'Server site': 'Default-First-Site-Name', 'Client site': 'Default-First-Site-Name'}
Connecting to debian-dc2.mondomaine.lan using SSH to add myself as remote device, add sysvol sync and get syncthing configuration...
Traceback (most recent call last):
  File "/opt/tis-sysvolsync/sysvolsync.py", line 430, in <module>
    main()
  File "/opt/tis-sysvolsync/sysvolsync.py", line 420, in main
    syncthing.add_mutual_sysvol_sync(local_dc,remote_dc)
  File "/opt/tis-sysvolsync/sysvolsync.py", line 293, in add_mutual_sysvol_sync
    remote_jsonconfig = subprocess.check_output('ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no %s python3 /opt/tis-sysvolsync/sysvolsync.py -ldebug -f /var/log/sysvolbind.log add-remote %s %s tcp://%s:%s' % (
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no debian-dc2.mondomaine.lan python3 /opt/tis-sysvolsync/sysvolsync.py -ldebug -f /var/log/sysvolbind.log add-remote SAF4TGP-RAASEMZ-JCYHRWR-ER4G2V4-2WGVTGN-XOVSZ4T-SARXPBP-RLGWCQK debian-dc1.mondomaine.lan tcp://debian-dc1.mondomaine.lan:22001' returned non-zero exit status 255.
```

**Comment by silkPK** [comment]
As mentioned in issue #2, Restarting both services **in all node** solved 

`systemctl restart tis-sysvolsync
systemctl restart tis-sysvolacl`
