### ISSUE TITLE
Cannot configure the syncronisation

### ISSUE THREAD

**Issue by flx-666** [tranquilit/tis-sysvolsync#9]
Hello,
I just installed 2 samba DCs on debian and followed the installation of tis-sysvolsync according to this page: [https://samba.tranquil.it/doc/en/samba_advanced_methods/samba_tis_sysvolsync.html](url)

When trying to configure, I either get this error;

```
adadmin@dc01:~$ /opt/tis-sysvolsync/sysvolsync.py configure
ltdb: tdb(/var/lib/samba/private/sam.ldb): tdb_open_ex: could not open file /var/lib/samba/private/sam.ldb: Permission denied

Unable to open tdb '/var/lib/samba/private/sam.ldb': Permission denied
Failed to connect to '/var/lib/samba/private/sam.ldb' with backend 'tdb': Unable to open tdb '/var/lib/samba/private/sam.ldb': Permission denied
Traceback (most recent call last):
  File "/opt/tis-sysvolsync/sysvolsync.py", line 76, in <module>
    samdb = SamDB(url='/var/lib/samba/private/sam.ldb', session_info=system_session(),credentials=creds, lp=lp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/samba/samdb.py", line 90, in __init__
    super().__init__(url=url, lp=lp, modules_dir=modules_dir,
  File "/usr/lib/python3/dist-packages/samba/__init__.py", line 113, in __init__
    self.connect(url, flags, options)
  File "/usr/lib/python3/dist-packages/samba/samdb.py", line 106, in connect
    super().connect(url=url, flags=flags, options=options)
_ldb.LdbError: (50, "Unable to open tdb '/var/lib/samba/private/sam.ldb': Permission denied")
adadmin@dc01:~$ 
```

or, if I sudo it, I get this:

```
adadmin@dc01:~$ sudo /opt/tis-sysvolsync/sysvolsync.py configure
[sudo] password for adadmin: 
2024-12-10 10:35:50,624 CRITICAL Error in data : b'CSRF Error\n' for path system/status
Traceback (most recent call last):
  File "/opt/tis-sysvolsync/sysvolsync.py", line 429, in <module>
    main()
  File "/opt/tis-sysvolsync/sysvolsync.py", line 368, in main
    syncthing = SyncThing()
                ^^^^^^^^^^^
  File "/opt/tis-sysvolsync/sysvolsync.py", line 106, in __init__
    self.id = self.get_syncthing_id()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tis-sysvolsync/sysvolsync.py", line 177, in get_syncthing_id
    return self.syncthing_rest_get('system/status')['myID']
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tis-sysvolsync/sysvolsync.py", line 150, in syncthing_rest_get
    return json.loads(data.content or '{}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
Am I doing something wrong? Is there a missing depedency on my systems?
This happen on both DCs...

Thanks in advance for your help,
Felix

**Comment by flx-666** [comment]
So, I retried the whole process as root, and allowed root ssh login, and it succeeded...
The sudo in the commands is useless in that case...

So for me:
sudo su -
nano /etc/ssh/sshd_config
Add "PermitRootLogin yes"
ssh root@ubuntu-server

Then install and configure
